import type { Command } from "commander";
import type { PageRenderer } from "./PageRenderer.js";

/** Banner marking the reference as generated — surfaced to anyone who opens the file. */
export const GENERATED_BANNER = "<!-- Generated by `pnpm docs:gen`. Do not edit by hand. -->";

/**
 * Renders the user-facing command reference straight from the live commander program, so it can
 * never drift from the CLI. Hidden groups (`_hook`, `_dev`) are excluded — they are not public.
 */
export class CommandReferenceRenderer implements PageRenderer<Command> {
  render(program: Command): string {
    const publicCommands = program.commands.filter((cmd) => !cmd.name().startsWith("_"));
    const parts: string[] = ["# jejak — command reference", "", GENERATED_BANNER, ""];

    for (const cmd of publicCommands) {
      const help = cmd.helpInformation().trimEnd();
      parts.push(`## \`jejak ${cmd.name()}\``, "", "```text", help, "```", "");
    }

    return `${parts.join("\n").trimEnd()}\n`;
  }
}
